import type { Metadata } from 'next';
import { Hahmlet } from 'next/font/google';
import './globals.css';
import { ReactNode } from 'react';
import NavBar from '@/components/NavBar';

const inter = Hahmlet({ subsets: ['latin', 'latin-ext', 'vietnamese'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
  hero,
  best,
  products,
  reviews,
  footer,
}: {
  children: ReactNode;
  hero: ReactNode;
  best: ReactNode;
  products: ReactNode;
  reviews: ReactNode;
  footer: ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`-bg--Black ${inter.className} hidden-scroll overflow-x-hidden`}
      >
        <NavBar />
        {children}
        {hero}
        {best}
        {products}
        {reviews}
        {footer}
      </body>
    </html>
  );
}
